import "./src/styles/global.css"
import "./src/components/HeaderComponents/header.css"
import "./src/components/FooterComponent/footer.css"
import "./src/components/HeroComponent/hero.css"
import "./src/components/TourCardComponent/TourCard.css"
